Footer Web and Hero Section
talyaron/freedi-web pull request #4
Opened 2024-06-24 20:05 UTC by Reshex

Changed footer component and scss, also added a new component for the hero section and added scss.
I haven't separated the pull request because i was waiting for a reply regarding the background and the font, and didn't want to wait in order to continue to the next task.
In the future ill make a separated branches for each section or feature.

2024-06-25 06:30 UTC, vladbyk89 commented on src/components/Pages/HomeSections/footer/footerStyle.scss
> +    background-color: $BackgroundColor;
General colors that will be later reused in other CSS files should be defined in globals.scss

2024-06-25 07:09 UTC, talyaron requested changes
Hi Bar,

Please look at the footer in mobile mode, and you will be able to see that it is not mobile frendly. please consult with Mash.

2024-06-25 07:14 UTC, talyaron requested changes
Also, the Hero Section is not responsive. 
and please look at the image:
 <Image style={{ width: "38rem", height: "35rem" }} className="heroSectionImg" src={heroSectionImg} alt="Hero Section" />
the constant style should be only on the scss.

Thanks

2024-06-27 03:38 UTC, talyaron requested changes
Hi bar, good work.
I need two changes:
- make the scss a module (css module). 
- about the varibales, please put them on the global.scss, with this method: --variable...

2024-06-29 13:39 UTC, vladbyk89 commented
Good job so far. I have a few comments.
1) Make sure the text aligns the way it is presented in figma.
2) The bottom part, where the arrow is, could be shorter. (compare with figma design)

2024-06-29 18:18 UTC, Reshex commented
> Good job so far. I have a few comments.
> 
> 1. Make sure the text aligns the way it is presented in figma.
> 2. The bottom part, where the arrow is, could be shorter. (compare with figma design)

Hey Vladi, thank you for the feedback, I believe that you were referring only to the footer, I fixed the problems and also fixed some problems in the hero section component.
As i said before, I accidently made a mistake that both of the components are at the same branch, for the next task I will use another branch.

2024-06-30 05:40 UTC, talyaron approved these changes
Well done

2024-07-02 08:15 UTC, merged